/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#1a1c1c',
        'secondary-fixed-dim': '#ffba20',
        'on-tertiary-fixed-variant': '#783200',
        'surface-variant': '#e2e2e2',
        'surface-bright': '#f9f9f9',
        'tertiary-fixed-dim': '#ffb690',
        'on-surface-variant': '#5b403f',
        'surface-container-highest': '#e2e2e2',
        'on-secondary-fixed-variant': '#5e4200',
        background: '#f9f9f9',
        'tertiary-container': '#c05400',
        'primary-fixed-dim': '#ffb3b1',
        'surface-container-high': '#e8e8e8',
        primary: '#b7122a',
        'surface-tint': '#bb162c',
        'on-primary': '#ffffff',
        'secondary-fixed': '#ffdea8',
        'inverse-surface': '#2f3131',
        'on-primary-fixed-variant': '#92001c',
        'outline-variant': '#e4bebc',
        secondary: '#7c5800',
        'on-tertiary-container': '#fffbff',
        'inverse-primary': '#ffb3b1',
        'primary-fixed': '#ffdad8',
        error: '#ba1a1a',
        'primary-container': '#db313f',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#341100',
        'surface-container-low': '#f3f3f3',
        tertiary: '#994100',
        'tertiary-fixed': '#ffdbca',
        'on-secondary-fixed': '#271900',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'on-background': '#1a1c1c',
        outline: '#8f6f6e',
        'error-container': '#ffdad6',
        surface: '#f9f9f9',
        'on-primary-container': '#fffbff',
        'surface-dim': '#dadada',
        'inverse-on-surface': '#f1f1f1',
        'on-secondary-container': '#6b4b00',
        'secondary-container': '#feb700',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#410007',
        'surface-container': '#eeeeee',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '32px',
        'container-padding': '20px',
        '2xl': '48px',
        base: '4px',
        gutter: '16px',
        sm: '12px',
        xs: '8px',
        lg: '24px',
        md: '16px',
      },
      fontFamily: {
        'body-lg': ['Be Vietnam Pro', 'sans-serif'],
        'label-md': ['Be Vietnam Pro', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'price-display': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'headline-xl': ['Montserrat', 'sans-serif'],
        'label-lg': ['Be Vietnam Pro', 'sans-serif'],
        'body-md': ['Be Vietnam Pro', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'price-display': ['22px', { lineHeight: '28px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
